In [1]:
import numpy as np
print(~np.array(False))

True


In [1]:
# 快速创建指定大小的递进矩阵
import numpy as np

aH = 100
aW = 100
y = np.arange(aH).repeat(aW).reshape(aW, -1)
print(y)

[[ 0  0  0 ...  0  0  0]
 [ 1  1  1 ...  1  1  1]
 [ 2  2  2 ...  2  2  2]
 ...
 [97 97 97 ... 97 97 97]
 [98 98 98 ... 98 98 98]
 [99 99 99 ... 99 99 99]]


In [2]:
# 矩阵运算
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
print(np.setdiff1d(a, b))

[1 2]


In [1]:
#Truth value testing
#all(a[, axis, out, keepdims, where])
#any(a[, axis, out, keepdims, where]

True

In [5]:
import numpy as np

np.logical_xor(1,0)
print(0 and 1)

0


In [6]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
import numpy as np
a = np.eye(4)
b = np.eye(4, k=-2)
print(a)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [16]:
#高阶用法
labels = np.array([[1], [2], [0], [1]])
res = np.eye(len(labels-1))[labels.reshape(-1)]
print(res)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [21]:
A = np.array([[3, 1], [1, 2]])
y = np.array([9, 8])
x = np.linalg.solve(A, y)
print(x)

'''
3x_0 + x_1 = 9
x_0 + 2x_1 = 8
'''

[2. 3.]


'\n3x_0 + x_1 = 9\nx_0 + 2x_1 = 8\n'

In [22]:
print(np.allclose(np.dot(A, x), y))

True


In [14]:
x = np.array([[3, 1], [1, 2]])
y = np.array([[3, 1], [2, 2]])
a = np.equal(x, y)
print(a)
b = np.all(a, axis=-1)
print(b)

[[ True  True]
 [False  True]]
[ True False]


In [13]:
l = [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]
print(l)
l = np.stack(l, axis=-1)
print(l)

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


In [1]:
import numpy as np
x = np.array([[1, 2, 1], [3, 1, 2]])
print(x.argmax(axis=1))

[1 0]


In [ ]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randn(4, 3), columns =list('bde'), index=['utah','ohio','texas','oregon'])
print(df)

operator = lambda x: x.max() - x.min()
f = df.apply(operator)
f2 = df.apply(operator, axis=1)
print(f)
print(f2)